pagos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # PAGOS
    path('', views.index, name="pagos_index"),
    path('socio/<int:id>', views.pagos_socio, name="pagos_socio"),
    # path('create', views.create, name="socios_create"),
    path('update/<int:id>', views.update, name="pagos_update"),
    # path('show/<int:id>', views.show, name="socios_show"),
    path('delete/<int:id>', views.delete, name="pagos_delete"),
    path('generar_cuotas', views.generar_cuotas, name="generar_cuotas"),
    path('marcar_pago/<int:id>', views.marcar_pago, name="marcar_pago"),
    path('nuevo_cargo/<int:id>', views.nuevo_cargo, name="pagos_nuevo_cargo"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('socios.urls')),
    path('pagos/', include('pagos.urls')),
    path('documentos/', include('documentos.urls')),
    path('agenda/', include('agenda.urls')),
    path('rutinas/', include('rutinas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # SOCIOS
    path('', views.index, name="socios_index"),
    path('create', views.create, name="socios_create"),
    path('update/<int:id>', views.update, name="socios_update"),
    path('show/<int:id>', views.show, name="socios_show"),
    path('delete/<int:id>', views.delete, name="socios_delete"),

    # CUOTAS
    path('cuotas', views.cuotas_index, name="cuotas_index"),
    path('cuotas/create', views.cuotas_create, name="cuotas_create"),
    path('cuotas/update/<int:id>', views.cuotas_update, name="cuotas_update"),
    # path('show/<int:id>', views.show, name="dependencias_show"),
    path('cuotas/delete/<int:id>', views.cuotas_delete, name="cuotas_delete"),

    # HORARIOS
    # path('cuotas', views.cuotas_index, name="cuotas_index"),
    path('horarios/create/<int:id>', views.horarios_create, name="horarios_create"),
    path('horarios/update/<int:id>', views.horarios_update, name="horarios_update"),
    # path('show/<int:id>', views.show, name="dependencias_show"),
    # path('cuotas/delete/<int:id>', views.cuotas_delete, name="cuotas_delete"),
]

socios/models.py
from django.db import models

class Socio(models.Model):
    ESTADO_SOCIO = [
        ('ACTIVO', 'Activo'),
        ('INACTIVO', 'Inactivo')
    ]

    nombre = models.CharField("Nombre", max_length=50)
    apellido = models.CharField("Apellido", max_length=50)
    fechanacimiento = models.DateField("Fecha de Nacimiento", blank=True, null=True, auto_now=False, auto_now_add=False)
    dni = models.IntegerField("DNI", blank=True, null=True)
    telefono = models.CharField("Telefono", max_length=50, blank=True)
    direccion = models.CharField("Direccion", max_length=50, blank=True)
    email = models.EmailField("Email", max_length=254, blank=True)
    estado = models.CharField("Estado", max_length=50, choices=ESTADO_SOCIO)
    observaciones = models.TextField("Observaciones")
    cuota = models.ForeignKey("socios.Cuota", on_delete=models.RESTRICT, related_name="cuota_socio")

    def __str__(self):
        return f'{self.apellido}, {self.nombre}'

class Cuota(models.Model):
    concepto = models.CharField("Concepto", max_length=50)
    monto = models.FloatField("Monto")

    def  __str__(self):
        return f"{self.concepto} - $ {self.monto}"
    
class Horario(models.Model):

    socio = models.ForeignKey('socios.Socio', verbose_name="Socio", on_delete=models.CASCADE, related_name="socio_horario", unique=True)
    lunes = models.BooleanField("Lunes", blank=True, null=True, default=False)
    lunesHorario = models.TimeField("Horario Lunes", auto_now=False, auto_now_add=False, blank=True, null=True)
    martes = models.BooleanField("Martes", blank=True, null=True, default=False)
    martesHorario = models.TimeField("Horario Martes", auto_now=False, auto_now_add=False, blank=True, null=True)
    miercoles = models.BooleanField("Miercoles", blank=True, null=True, default=False)
    miercolesHorario = models.TimeField("Horario Miercoles", auto_now=False, auto_now_add=False, blank=True, null=True)
    jueves = models.BooleanField("Jueves", blank=True, null=True, default=False)
    juevesHorario = models.TimeField("Horario Jueves", auto_now=False, auto_now_add=False, blank=True, null=True)
    viernes = models.BooleanField("Viernes", blank=True, null=True, default=False)
    viernesHorario = models.TimeField("Horario Viernes", auto_now=False, auto_now_add=False, blank=True, null=True)
    sabado = models.BooleanField("Sabado", blank=True, null=True, default=False)
    sabadoHorario = models.TimeField("Horario Sabado", auto_now=False, auto_now_add=False, blank=True, null=True)
    domingo = models.BooleanField("Domingo", blank=True, null=True, default=False)
    domingoHorario = models.TimeField("Horario Domingo", auto_now=False, auto_now_add=False, blank=True, null=True)
    
    def horario_id(self):
        return f'{self.id}'

    def __str__(self):
        salida = ""
        if self.lunes == True:
            salida += str('LUN (' + self.lunesHorario.strftime("%H:%M") + '), ')
        if self.martes == True:
            salida += str('MAR (' + self.martesHorario.strftime("%H:%M") + '), ')
        if self.miercoles == True:
            salida += str('MIE (' + self.miercolesHorario.strftime("%H:%M") + '), ')
        if self.jueves == True:
            salida += str('JUE (' + self.juevesHorario.strftime("%H:%M") + '), ')
        if self.viernes == True:
            salida += str('VIE (' + self.viernesHorario.strftime("%H:%M") + '), ')
        if self.sabado == True:
            salida += str('SAB (' + self.sabadoHorario.strftime("%H:%M") + '), ')
        if self.domingo == True:
            salida += str('DOM (' + self.domingoHorario.strftime("%H:%M") + '), ')
        if salida == "":
            salida = f'{self.socio} No tiene horario definido.-'
        return salida

socios/forms.py
from django import forms
from .models import Socio, Cuota, Horario

class CuotaForm(forms.ModelForm):
    class Meta:
        model = Cuota
        fields = [
            'concepto',
            'monto'
        ]

    concepto = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Concepto', 'required': 'required', 'autofocus': 'autofocus'}))
    monto = forms.FloatField( widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Monto', 'required': 'required'}))

ESTADO_SOCIO = [
        ('ACTIVO', 'Activo'),
        ('INACTIVO', 'Inactivo')
    ]

class SocioForm(forms.ModelForm):
    class Meta:
        model = Socio
        fields = [
            'apellido',
            'nombre',
            'fechanacimiento',
            'dni',
            'telefono',
            'direccion',
            'email',
            'estado',
            'observaciones',
            'cuota'
        ]

    apellido = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido', 'required': 'required', 'autofocus': 'autofocus'}))
    nombre = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre', 'required': 'required'}))
    fechanacimiento = forms.DateField(widget=forms.DateInput(format = ('%Y-%m-%d'), attrs={'class': 'form-control', 'type': 'date'}) , required=False)
    dni = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'type': 'number'}), required=False)
    telefono = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefono'}), required=False)
    direccion = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Direccion'}), required=False)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'email', 'type': 'email'}), required=False)
    estado = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Estado'}) , choices=ESTADO_SOCIO)
    cuota = forms.ModelChoiceField(Cuota.objects.all(), empty_label=None, widget=forms.Select( attrs={ 'class': 'form-control', 'placeholder': 'Tipo de Cuota'} ))
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 8rem;'}), required=False)
    

class HorarioForm(forms.ModelForm):
    class Meta:
        model = Horario
        fields = [
            # 'socio',
            'lunes',
            'lunesHorario',
            'martes',
            'martesHorario',
            'miercoles',
            'miercolesHorario',
            'jueves',
            'juevesHorario',
            'viernes',
            'viernesHorario',
            'sabado',
            'sabadoHorario',
            'domingo',
            'domingoHorario'
        ]

    # socio = forms.ModelChoiceField(Socio.objects.all(), empty_label=None, widget=forms.Select( attrs={ 'class': 'form-control', 'placeholder': 'Socio'} ), required=False)
    lunes = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    lunesHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)
    martes = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    martesHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)
    miercoles = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    miercolesHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)
    jueves = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    juevesHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)
    viernes = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    viernesHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)
    sabado = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    sabadoHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)
    domingo = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False)
    domingoHorario = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}), required=False)

socios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Cuota, Socio, Horario
from .forms import CuotaForm, SocioForm, HorarioForm
from pagos.models import Pago
from django.db.models import Q
from documentos.models import Documento

# SOCIOS
def index(request):
    socios = Socio.objects.all()
    context = {
        'socios': socios
    }
    return render(request, 'socios_index.html', context)

def create(request):
    form = SocioForm()
    if request.method == 'POST':
        form = SocioForm(request.POST)

        try:
            if form.is_valid():
                socioNuevo = form.save()
                # inicializar horarios
                Horario.objects.create(socio = socioNuevo)
                messages.success(request, 'Datos del socio guardados con exito.')
                return redirect('socios_index')
            else:
                messages.warning(request, 'Error durante la carga de datos')
                return render(request, 'socios_create.html', context = {'form': form})
        except Exception as e:
            messages.warning(request, f'Error al realizar la carga de datos. {e}')
            return redirect('socios_index')

    context = {
        'form': form,
    }
    return render(request, 'socios_create.html', context)

def update(request, id=id):
    obj = get_object_or_404(Socio, pk=id)
    form = SocioForm(request.POST or None, instance=obj)

    if form.is_valid():
        try:
            form.save()
            messages.success(request, 'Datos actualizados con exito.-')
            return redirect('socios_index')
        except Exception as e:
            messages.warning(request, f'Error al actualizar los datos. {e}')
            return redirect('socios_index')

    context = {
        'form': form
    }
    return render(request, 'socios_create.html', context)

def delete(request, id=id):
    socio = get_object_or_404(Socio, pk=id)
    if request.method == 'POST':
        try:
            socio.delete()
            messages.success(request, 'Datos eliminados con exito.-')
            return redirect('socios_index')
        except Exception as e:
            messages.warning(request, f'No es posible eliminar los datos del socio, posee registros relacionados. {e}')
            return redirect('socios_index')
    context = {
        'socio': socio
    }
    return render(request, 'socios_delete.html', context)

def show(request, id=id):
    socio = get_object_or_404(Socio, pk=id)
    pagos = Pago.objects.filter(socio = socio.id)[:5]
    documentos = Documento.objects.filter(socio = socio.id)
    if Pago.objects.filter( Q(socio = socio.id) and Q(estado = 'IMPAGO') ).count() == 0:
        aldia = 'Al Dia'
    else:
        aldia = 'Con Deuda'

    context = {
        'socio': socio,
        'pagos': pagos,
        'aldia': aldia,
        'documentos': documentos
    }
    return render(request, 'socios_show.html', context)

# CUOTAS
def cuotas_index(request):
    cuotas = Cuota.objects.all()
    context = {
        'cuotas': cuotas
    }
    return render(request, 'cuotas_index.html', context)

def cuotas_create(request):
    form = CuotaForm()
    if request.method == 'POST':
        form = CuotaForm(request.POST)

        try:
            if form.is_valid():
                resultado = form.save()
                messages.success(request, 'Categoria de cuota creada con exito.')
                return redirect('cuotas_index')
            else:
                messages.warning(request, 'Error durante la carga de datos')
                return render(request, 'cuotas_create.html', context = {'form': form})
        except Exception as e:
            messages.warning(request, f'Error al realizar la carga de datos. {e}')
            return redirect('cuotas_index')

    context = {
        'form': form,
    }
    return render(request, 'cuotas_create.html', context)

def cuotas_update(request, id=id):
    obj = get_object_or_404(Cuota, pk=id)
    form = CuotaForm(request.POST or None, instance=obj)

    if form.is_valid():
        try:
            form.save()
            messages.success(request, 'Datos actualizados con exito.-')
            return redirect('cuotas_index')
        except Exception as e:
            messages.warning(request, f'Error al actualizar los datos. {e}')
            return redirect('cuotas_index')

    context = {
        'form': form
    }
    return render(request, 'cuotas_create.html', context)

def cuotas_delete(request, id=id):
    cuota = get_object_or_404(Cuota, pk=id)
    if request.method == 'POST':
        try:
            cuota.delete()
            messages.success(request, 'Datos eliminados con exito.-')
            return redirect('cuotas_index')
        except Exception as e:
            messages.warning(request, f'No es posible eliminar los datos de la cuota, posee registros relacionados. {e}')
            return redirect('cuotas_index')
    context = {
        'cuota': cuota
    }
    return render(request, 'cuotas_delete.html', context)


# HORARIOS

def horarios_create(request, id=id):
    form = HorarioForm()
    socio = get_object_or_404(Socio, pk=id)

    if request.method == 'POST':
        form = HorarioForm(request.POST)
        if form.is_valid():
            try:
                instancia = form.save(commit=False)
                instancia.socio = Socio.objects.get(pk=id)
                instancia.save()
                messages.success(request, f'Horario para socio ({socio}) fue actualizado con exito.-')
                return redirect('socios_index')
            except Exception as e:
                messages.success(request, f'No fue posible actualizar horarios de socio ({socio}. Error: {e}.-)')
                return redirect('socios_index')


    context = {
        'form': form,
        'socio': socio
    }
    return render(request, 'horarios/horarios_create.html', context)

def horarios_update(request, id=id):
    obj = get_object_or_404(Horario, pk=id)
    form = HorarioForm(request.POST or None, instance=obj)

    if form.is_valid():
        try:
            instancia = form.save()
            messages.success(request, f'Horario de {instancia.socio} fue actualizado con exito.-')
            return redirect('socios_index')
        except Exception as e:
            messages.warning(request, f'No fue posible actualizar horarios de socio ({instancia.socio}. Error: {e}.-)')
            return redirect('socios_index')

    context = {
        'form': form,
        'socio': obj.socio
    }
    return render(request, 'horarios/horarios_create.html', context)

socios/templates/horarios/horarios_create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Horarios</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Horarios (Nuevo)</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
  
      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">

            <div class="col-lg">
              {% if messages %}
              {% comment %} ALERTAS {% endcomment %}
                {% for message in messages %}
                    {% if message.tags %}
                      <div class="alert alert-{{ message.tags }}">
                        {% comment %} <h5><i class='bx bx-info-circle bx-md'></i></h5> {% endcomment %}
                        <ul style="margin-bottom: 0px;">
                          <li class="">{{ message }}</li>                   
                        </ul>
                      </div>
                  {% endif %}
                {% endfor %}
              {% comment %} FIN ALERTAS {% endcomment %}
              {% endif %}

              {% if form.errors %}
              <div class="alert alert-danger">
                {{form.errors}}
              </div>
              {% endif %}
              

              <div class="card card-primary card-outline">

                <div class="card-header">
                  <h5 class="card-title">Horarios - {{socio}}</h5>

                </div>

                <form action="" method="POST">
                    <div class="card-body">
                        
                            {% csrf_token %}
                            
                            <input type="hidden" name="socio" id="id_socio" value="{{socio.id}}">

                            <div class="row">
                                <div class="col-4">
                                    <h4 class="float-right">Lunes</h4>
                                </div>
                                <div class="col-1 float-left">
                                    {{form.lunes}}
                                    {{form.lunes.errors}}
                                </div>
                                <div class="col-2">
                                    {{form.lunesHorario}}
                                    {{form.lunesHorario.errors}}
                                </div>
                                <div class="col"></div>
                            </div>
                            
                            <hr>

                            <div class="row">
                                <div class="col-4">
                                    <h4 class="float-right">Martes</h4>
                                </div>
                                <div class="col-1 float-left">
                                    {{form.martes}}
                                </div>
                                <div class="col-2">
                                    {{form.martesHorario}}
                                </div>
                                <div class="col"></div>
                            </div>

                            <hr>

                            <div class="row">
                              <div class="col-4">
                                  <h4 class="float-right">Miercoles</h4>
                              </div>
                              <div class="col-1 float-left">
                                  {{form.miercoles}}
                              </div>
                              <div class="col-2">
                                  {{form.miercolesHorario}}
                              </div>
                              <div class="col"></div>
                          </div>

                          <hr>

                          <div class="row">
                            <div class="col-4">
                                <h4 class="float-right">Jueves</h4>
                            </div>
                            <div class="col-1 float-left">
                                {{form.jueves}}
                            </div>
                            <div class="col-2">
                                {{form.juevesHorario}}
                            </div>
                            <div class="col"></div>
                        </div>

                        <hr>

                        <div class="row">
                          <div class="col-4">
                              <h4 class="float-right">Viernes</h4>
                          </div>
                          <div class="col-1 float-left">
                              {{form.viernes}}
                          </div>
                          <div class="col-2">
                              {{form.viernesHorario}}
                          </div>
                          <div class="col"></div>
                      </div>

                      <hr>

                        <div class="row">
                          <div class="col-4">
                              <h4 class="float-right">Sabado</h4>
                          </div>
                          <div class="col-1 float-left">
                              {{form.sabado}}
                          </div>
                          <div class="col-2">
                              {{form.sabadoHorario}}
                          </div>
                          <div class="col"></div>
                      </div>

                      <hr>

                        <div class="row">
                          <div class="col-4">
                              <h4 class="float-right">Domingo</h4>
                          </div>
                          <div class="col-1 float-left">
                              {{form.domingo}}
                          </div>
                          <div class="col-2">
                              {{form.domingoHorario}}
                          </div>
                          <div class="col"></div>
                      </div>
                        
                    </div>

                    <div class="card-footer">
                      <a href="{% url 'socios_index' %}" tabindex="-1" class="btn btn-success float-left"><i class='bx bx-arrow-back'></i> Volver</a>
                        <button type="submit" class="btn btn-primary float-right"><i class='bx bx-check-circle'></i> Guardar</button>
                    </div>
                </form>
                


              </div>

            </div>
            <!-- /.col-md-6 -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
{% endblock content %}

{% block scripts %}
<script>
window.onload = (event) =>{
  comprobarChecks('id_lunes')
  comprobarChecks('id_martes', '')
  comprobarChecks('id_miercoles', '')
  comprobarChecks('id_jueves', '')
  comprobarChecks('id_viernes', '')
  comprobarChecks('id_sabado', '')
  comprobarChecks('id_domingo', '')
};

document.getElementById('id_lunes').onchange = function() {comprobarChecks('id_lunes', 'onChange')};
document.getElementById('id_martes').onchange = function() {comprobarChecks('id_martes', 'onChange')};
document.getElementById('id_miercoles').onchange = function() {comprobarChecks('id_miercoles', 'onChange')};
document.getElementById('id_jueves').onchange = function() {comprobarChecks('id_jueves', 'onChange')};
document.getElementById('id_viernes').onchange = function() {comprobarChecks('id_viernes', 'onChange')};
document.getElementById('id_sabado').onchange = function() {comprobarChecks('id_sabado', 'onChange')};
document.getElementById('id_domingo').onchange = function() {comprobarChecks('id_domingo', 'onChange')};

function comprobarChecks(id, evento){
  var horario_id = id + 'Horario'
  var check = document.getElementById(id)
  document.getElementById(horario_id).disabled = !check.checked;
  if (evento == 'onChange'){
    document.getElementById(horario_id).value = ""
    if (check.checked){
      document.getElementById(horario_id).setAttribute("required", "");
    }else{
      document.getElementById(horario_id).removeAttribute("required");
    }
  }
  
    
}
</script>
{% endblock scripts %}