pagos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # PAGOS
    path('', views.index, name="pagos_index"),
    path('socio/<int:id>', views.pagos_socio, name="pagos_socio"),
    # path('create', views.create, name="socios_create"),
    path('update/<int:id>', views.update, name="pagos_update"),
    # path('show/<int:id>', views.show, name="socios_show"),
    path('delete/<int:id>', views.delete, name="pagos_delete"),
    path('generar_cuotas', views.generar_cuotas, name="generar_cuotas"),
    path('marcar_pago/<int:id>', views.marcar_pago, name="marcar_pago"),
    path('nuevo_cargo/<int:id>', views.nuevo_cargo, name="pagos_nuevo_cargo"),
]

rutinas/urls.py
from django.urls import path
from rutinas import views

urlpatterns = [
    # RUTINAS
    path('', views.index, name="rutinas_index"),
    # path('socio/<int:id>', views.pagos_socio, name="pagos_socio"),
    # path('create/turno', views., name="rutinas_create"),
    # path('create/evento', views.create_evento, name="agenda_create_evento"),
    # path('update/<str:evento>/<int:id>', views.update, name="agenda_update"),
    path('show/<int:id>/<int:agenda>', views.show, name="rutinas_show"),
    # path('delete/<int:id>', views.delete, name="agenda_delete"),
    # path('generar_mes', views.generar_mes, name="agenda_generar_mes"),

    # SERIES
    # path('', views.index, name="rutinas_index"),
    # path('socio/<int:id>', views.pagos_socio, name="pagos_socio"),
    path('serie/create/', views.series_create, name="series_create"),
    # path('create/evento', views.create_evento, name="agenda_create_evento"),
    # path('update/<str:evento>/<int:id>', views.update, name="agenda_update"),
    # path('show/<int:id>/<int:agenda>', views.show, name="rutinas_show"),
    path('serie/delete/<int:id>', views.series_delete, name="series_delete"),
    # path('generar_mes', views.generar_mes, name="agenda_generar_mes"),

    # EJERCICIOS
    path('ejercicios/', views.ejercicios_index, name="ejercicios_index"),
    # path('socio/<int:id>', views.pagos_socio, name="pagos_socio"),
    # path('serie/create/', views.series_create, name="series_create"),
    path('ejercicios/create', views.ejercicios_create, name="ejercicios_create"),
    path('ejercicios/update/<int:id>', views.ejercicios_update, name="ejercicios_update"),
    # path('show/<int:id>/<int:agenda>', views.show, name="rutinas_show"),
    path('ejercicios/delete/<int:id>', views.ejercicios_delete, name="ejercicios_delete"),
    # path('generar_mes', views.generar_mes, name="agenda_generar_mes"),

    # ELEMENTOS
    path('elementos/create/<int:contenedor_id>', views.elementos_create, name="elementos_create"),
    path('elementos/update/<int:id>', views.elementos_update, name="elementos_update"),
    path('elementos/elementos_delete/<int:id>', views.elementos_delete, name="elementos_delete"),
    path('elementos/ejercicios_ajax/', views.ejercicios_ajax, name="ejercicios_ajax"),

    # MODELOS RUTINAS
    path('modelos/', views.modelos_index, name="modelos_rutinas_index"),
    path('modelos/create/', views.modelos_create, name="modelos_rutinas_create"),
    path('modelos/update/<int:id>', views.modelos_update, name="modelos_rutinas_update"),
    path('modelos/delete/<int:id>', views.modelos_delete, name="modelos_rutinas_delete"),
    path('modelos/show/<int:id>', views.modelos_show, name="modelos_rutinas_show"),
    # path('elementos/ejercicios_ajax/', views.ejercicios_ajax, name="ejercicios_ajax"),

    # MODELOS SERIES
    path('modelos/series/create', views.modelos_series_create, name="modelos_series_create"),
    # path('modelos/series/update/<int:id>', views.modelos_series_update, name="modelos_series_update"),
    path('modelos/series/delete/<int:id>', views.modelos_series_delete, name="modelos_series_delete"),

    # MODELOS ELEMENTOS
    path('modelos/elementos/create/<int:contenedor_id>', views.modelos_elementos_create, name="C"),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('socios.urls')),
    path('pagos/', include('pagos.urls')),
    path('documentos/', include('documentos.urls')),
    path('agenda/', include('agenda.urls')),
    path('rutinas/', include('rutinas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rutinas/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from socios.models import Socio
from agenda.models import Agenda

# RUTINAS
class Rutina(models.Model):
    socio = models.ForeignKey(Socio, verbose_name="Socio", on_delete=models.CASCADE, related_name="rutina_socio")
    agenda = models.ForeignKey(Agenda, verbose_name="Agenda", on_delete=models.CASCADE, related_name="rutina_agenda")

    class Meta:
        unique_together = ('socio', 'agenda')

    def __str__(self):
        return f'{self.socio} - {self.agenda.fecha}'

# CONTENEDORES
class Contenedor(models.Model):
    rutina = models.ForeignKey('rutinas.Rutina', verbose_name="Rutina", on_delete=models.CASCADE, related_name="contenedor_rutina")
    contenedor = models.CharField("Serie", max_length=50)

# ELEMENTOS_CONTENEDOR
class Elemento(models.Model):
    contenedor = models.ForeignKey('rutinas.Contenedor', verbose_name="Contenedor", on_delete=models.CASCADE, related_name="elemento_contenedor")
    ejercicio = models.ForeignKey('rutinas.Ejercicio', verbose_name="Ejercicio", on_delete=models.RESTRICT, related_name="elemento_ejercicio")
    peso = models.FloatField("Peso", default = 0)
    repeticiones = models.IntegerField("Repeticiones", default = 0)

    def __str__(self):
        return f'{self.ejercicio}'

# EJERCICIOS
class Ejercicio(models.Model):
    
    ejercicio = models.CharField("Ejercicio", max_length=50)
    foto = models.FileField('Foto', upload_to ="documentos/ejercicios/fotos/", null=False, blank=False, validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])]) 
    video = models.FileField('Video', upload_to ="documentos/ejercicios/videos/", null=False, blank=False, validators=[FileExtensionValidator(['avi', 'mp4'])])

    def __str__(self):
        return f'{self.ejercicio}'

# -------------------------- MODELOS DE RUTINAS --------------------------

# RUTINA MODELO
class Rutina_modelo(models.Model):
    titulo = models.CharField("Titulo", max_length=100)
    descripcion = models.TextField("Descripcion")

    def __str__(self):
        return self.titulo

# SERIE MODELO
class Contenedor_modelo(models.Model):
    rutina = models.ForeignKey('rutinas.Rutina_modelo', verbose_name="Rutina", on_delete=models.CASCADE, related_name="contenedor_rutina_modelo")
    contenedor = models.CharField("Serie", max_length=50)

# ELEMENTOS_CONTENEDOR MODELO
class Elemento_modelo(models.Model):
    contenedor = models.ForeignKey('rutinas.Contenedor_modelo', verbose_name="Contenedor", on_delete=models.CASCADE, related_name="elemento_Contenedor_modelo")
    ejercicio = models.ForeignKey('rutinas.Ejercicio', verbose_name="Ejercicio", on_delete=models.RESTRICT, related_name="ejercicio_elemento_modelo")
    peso = models.FloatField("Peso", default = 0)
    repeticiones = models.IntegerField("Repeticiones", default = 0)

    def __str__(self):
        return f'{self.ejercicio}'

rutinas/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Rutina, Ejercicio, Elemento, Contenedor, Rutina_modelo, Contenedor_modelo
from agenda.models import Agenda
from socios.models import Socio
import datetime
from .forms import EjercicioForm, ElementoForm, RutinaModeloForm, ContenedorModeloSerieForm, ElementoModeloForm
from django.contrib import messages
from django.db.models import Q


# RUTINAS

def index(request):
    agenda = Agenda()
    context = {'fecha_hoy': datetime.date.today()}

    if request.method == 'POST':
        socio_query = request.POST.get('q')
        fecha_query = request.POST.get('fecha')
        
        # Si los filtros estan vacios, no pasa nada
        if socio_query == "" and fecha_query == "":
            return redirect('rutinas_index')

        # FILTRTADO
        agenda = Agenda.objects.all()

        if fecha_query != "":
            agenda = agenda.filter(fecha = fecha_query).order_by('-fecha')  

        if socio_query != "":
            agenda = agenda.filter( Q(socio__nombre__icontains = socio_query) | Q(socio__apellido__icontains = socio_query) ).order_by('-fecha')[:15]
        # FIN FILTRADO

        context.update({'fecha_hoy': datetime.datetime.strptime(fecha_query, '%Y-%m-%d').date()})
       
    else:
        agenda = Agenda.objects.filter(fecha = datetime.date.today()).order_by('-fecha')

    context.update({'agendas': agenda})

    return render(request, 'rutinas_index.html', context)

def show(request, id, agenda ):
    socio = Socio.objects.get(pk = id)
    agenda = Agenda.objects.get(pk = agenda )
    context = {}

    # al ingresar a show para la rutina. si la rutina NO existe, crea una nueva
    # de lo contrario, continua
    rutina = Rutina.objects.filter(socio = socio, agenda = agenda).first()
    if not rutina:
        Rutina.objects.create(socio = socio, agenda = agenda)

    rutina = Rutina.objects.filter(socio = socio, agenda = agenda).first()
    series = Contenedor.objects.filter(rutina = rutina).prefetch_related('elemento_contenedor')
    context.update({'series': series})

    context.update({'rutina': rutina})
    return render(request, 'rutinas_show.html', context)


# SERIES

def series_create(request):
    rutina_id = request.POST.get('rutina_id')
    serie = request.POST.get('serie')
    rutina = get_object_or_404(Rutina, pk = rutina_id)

    if request.method == 'POST':
        try:
            instancia = Contenedor.objects.create(contenedor = serie, rutina = rutina)
            messages.success(request, f'Serie {instancia.contenedor} cargada con exito')
            return redirect('rutinas_show', rutina.socio.id, rutina.agenda.id)
        except Exception as e:
            messages.warning(request, f'Error durante la carga de datos. Error: {e}')
            return redirect('rutinas_show', rutina.socio.id, rutina.agenda.id)
    else:
        return redirect('rutinas_show', rutina.socio.id, rutina.agenda.id)
    
def series_delete(request, id):
    serie = get_object_or_404(Contenedor, pk=id)
    if request.method == 'POST':
        try:
            nombre_serie_borrada = serie.contenedor
            rutina = Rutina.objects.get(pk = serie.rutina.id)
            instancia = serie.delete()
            messages.success(request, f'Serie {nombre_serie_borrada} eliminada con exito.-')
            return redirect('rutinas_show', rutina.socio.id, rutina.agenda.id)
        except Exception as e:
            messages.warning(request, f'No es posible eliminar los datos de la serie {nombre_serie_borrada}, posee registros relacionados. Error: {e}')
            return redirect('rutinas_show', rutina.socio.id, rutina.agenda.id)
    context = {
        'serie': serie
    }
    return render(request, 'series/series_delete.html', context)


# DETALLS DE LA SERIE (ELEMENTOS)

def elementos_create(request, contenedor_id):
    contenedor = Contenedor.objects.get(pk = contenedor_id)
    form = ElementoForm(request.POST or None, initial={'contenedor': contenedor})

    if form.is_valid():
        try:
            form.save()
            messages.success(request, 'Datos guardados con exito.-')
            return redirect('rutinas_show', contenedor.rutina.socio.id, contenedor.rutina.agenda.id) 
        except Exception as e:
            messages.warning(request, f'Error al actualizar los datos. {e}')
            return redirect('rutinas_show', contenedor.rutina.socio.id, contenedor.rutina.agenda.id) 

    context = {
        'form': form
    }
    return render(request, 'elementos/elementos_create.html', context)

def elementos_update(request, id):
    obj = get_object_or_404(Elemento, pk=id)
    form = ElementoForm(request.POST or None, instance=obj)

    if form.is_valid():
        # contenedor = Contenedor.objects.get(pk = obj.contenedor.id)
        try:
            form.save()
            messages.success(request, 'Datos actualizados con exito.-')
            return redirect('rutinas_show', obj.contenedor.rutina.socio.id, obj.contenedor.rutina.agenda.id)
        except Exception as e:
            messages.warning(request, f'Error al actualizar los datos. {e}')
            return redirect('rutinas_show', obj.rutina.socio.id, obj.rutina.agenda.id)

    context = {
        'form': form
    }
    return render(request, 'elementos/elementos_create.html', context)

def elementos_delete(request, id):
    elemento = get_object_or_404(Elemento, pk=id)

    if request.method == 'POST':
        try:
            contenedor = Contenedor.objects.get(pk = elemento.contenedor.id)
            elemento.delete()
            messages.success(request, 'Datos eliminados con exito.-')
            return redirect('rutinas_show', contenedor.rutina.socio.id, contenedor.rutina.agenda.id)
        except Exception as e:
            messages.warning(request, f'No es posible eliminar los datos del pago, posee registros relacionados. {e}')
            return redirect('rutinas_show', contenedor.rutina.socio.id, contenedor.rutina.agenda.id)
    context = {
        'elemento': elemento
    }
    return render(request, 'elementos/elementos_delete.html', context)


# EJERCICIOS

def ejercicios_index(request):
    context = {}
    ejercicios = Ejercicio()

    if request.method == 'POST':
        query = request.POST.get('q')
        ejercicios = Ejercicio.objects.filter(ejercicio__icontains = query)
        context.update({'q': query})
    else:
        ejercicios = Ejercicio.objects.all()[:50]

    context.update({
        'ejercicios': ejercicios,
    })
    return render(request, 'ejercicios/ejercicios_index.html', context)

def ejercicios_create(request):
    form = EjercicioForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        try:
            form.save()
            messages.success(request, 'Datos guardados con exito.-')
            return redirect('ejercicios_index') 
        except Exception as e:
            messages.warning(request, f'Error al actualizar los datos. {e}')
            return redirect('ejercicios_index') 

    context = {
        'form': form
    }
    return render(request, 'ejercicios/ejercicios_create.html', context)

def ejercicios_update(request, id):
    obj = get_object_or_404(Ejercicio, pk=id)
    form = EjercicioForm(request.POST or None, request.FILES or None, instance=obj)

    if form.is_valid():
        try:
            form.save()
            messages.success(request, 'Datos actualizados con exito.-')
            return redirect('ejercicios_index')
        except Exception as e:
            messages.warning(request, f'Error al actualizar los datos. {e}')
            return redirect('ejercicios_index')

    context = {
        'form': form
    }
    return render(request, 'ejercicios/ejercicios_create.html', context)

def ejercicios_delete(request, id):
    ejercicio = get_object_or_404(Ejercicio, pk=id)
    if request.method == 'POST':
        try:
            # MEJOR ESTO, PARA QUE NO SE DE EL CASO DE BORRAR LAS FOTOS Y NO LA EL CAMPO
            ejercicio.foto.delete()
            ejercicio.video.delete()
            ejercicio.delete()
            messages.success(request, 'Datos eliminados con exito.-')
            return redirect('ejercicios_index')
        except Exception as e:
            messages.warning(request, f'No es posible eliminar los datos del pago, posee registros relacionados. {e}')
            return redirect('ejercicios_index')
    context = {
        'ejercicio': ejercicio
    }
    return render(request, 'ejercicios/ejercicios_delete.html', context)

def ejercicios_ajax(request):
    q = request.GET.get('search')
    data = []

    ejercicios = Ejercicio.objects.filter(ejercicio__icontains = q)
    for ejercicio in ejercicios:
        data.append({'id': ejercicio.id, 'text': ejercicio.ejercicio})

    return JsonResponse(data, safe=False)


# MODELOS RUTINAS

def modelos_index(request):
    form = RutinaModeloForm()
    
    if request.method == 'POST':
        query = request.POST.get('q')
        modelos_rutinas = Rutina_modelo.objects.filter(titulo__icontains = query)[:50]
    else:
        modelos_rutinas = Rutina_modelo.objects.all()[:50]

    context = {
        'form': form,
        'rutinas': modelos_rutinas
    }
    return render(request, 'rutinas_modelos/modelos_index.html', context)

def modelos_create(request):
    if request.method == 'POST':
        form = RutinaModeloForm(request.POST or None)

        if form.is_valid():
            try:
                instance = form.save()
                messages.success(request, f'Rutina {instance.titulo} creada con exito')
                return redirect('modelos_rutinas_index')
            except Exception as e:
                messages.warning(request, f'Error al crear la rutina {instance.titulo}. Error: {e}')
                return redirect('modelos_rutinas_index')
    else:
        return redirect('modelos_rutinas_index')

def modelos_update(request, id):

rutinas/templates/rutinas_modelos/modelos_delete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Rutinas (MODELOS)</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Rutinas (MODELOS)</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
  
      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">

            <div class="col-lg">

              <div class="card card-primary card-outline">

                <div class="card-header">
                  <h5 class="card-title">Modelos de Rutinas</h5>

                </div>

                <form action="" method="POST">
                    <div class="card-body">
                        
                            {% csrf_token %}
                            
                            <div class="row">
                                <div class="col-md-2 col-sm-12">
                                    <i class='bx bx-error' style='color:#dc3545; font-size: 8rem'  ></i>
                                </div>
                                <div class="col-md-10 col-sm-12">
                                    <p>Esta a punto de eliminar ({{rutina.titulo}}), <strong>los registros eliminados no se podran recuperar.-</strong></p>
                                    <span style="color: #dc3545;">¿Desea continuar?</span>
                                </div>
                            </div>  
                    </div>

                    <div class="card-footer">
                        <a href="{% url 'modelos_rutinas_index' %}" class="btn btn-success float-left"><i class='bx bx-arrow-back'></i> Volver</a>
                        <button type="submit" class="btn btn-danger float-right"><i class='bx bx-trash'></i> Borrar</button>
                    </div>
                </form>
                


              </div>

            </div>
            <!-- /.col-md-6 -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
{% endblock content %}

rutinas/templates/rutinas_modelos/modelos_index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Rutinas (MODELOS)</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Rutinas (MODELOS)</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
  
      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">

            <div class="col-lg">

              {% if messages %}
              {% comment %} ALERTAS {% endcomment %}
                {% for message in messages %}
                    {% if message.tags %}
                      <div class="alert alert-{{ message.tags }}">
                        {% comment %} <h5><i class='bx bx-info-circle bx-md'></i></h5> {% endcomment %}
                        <ul style="margin-bottom: 0px;">
                          <li class="">{{ message }}</li>                   
                        </ul>
                      </div>
                  {% endif %}
                {% endfor %}
              {% comment %} FIN ALERTAS {% endcomment %}
              {% endif %}

              <div class="card card-primary card-outline collapsed-card">
                
                <div class="card-header">
                  <form action="" method="POST">
                      <div class="row">
                        <div class="col-lg-5 col-sm-12">
                          {% csrf_token %}
                          <input type="text" id="q" name="q" class="form-control" placeholder="Buscar por nombre" value="{{q}}">
                        </div>    
                        <div class="col-lg-5 col-sm-12">
                          <button type="submit" class="btn btn-primary btn-flat">Buscar</button>
                        </div>
                        
                        <div class="col-lg-2 col-sm-12">
                          <button title="Limpiar Filtros" onclick="ClearFields();"  class="btn btn-primary btn-flat btn-sm float-right mr-3"><i class='bx bx-reset'></i></button>
                        </div>
                      </div>
                  
                </div>
              </form>
              </div>

              <div class="card card-primary card-outline">
                <div class="card-header">
                  <h5 class="card-title">Modelos de Rutinas</h5>

                  <a href="#" data-toggle="modal" data-target="#exampleModalCenter" class="btn btn-primary btn-sm float-right"><i class='bx bx-medical'></i> Crear Rutina</a>

                </div>
                <!-- /.card-header -->
                <div class="card-body">

                
                {% if rutinas %}
                <div class="card-body table-responsive p-0">

                  
                  <table class="table table-hover text-nowrap">
                    <thead>
                      <tr>
                        <th>Titulo</th>
                        <th>Descripcion</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>

                      {% for rutina in rutinas %}
                      <tr>
                        <td>{{rutina.titulo}}</td>
                        <td>{{rutina.descripcion}}</td>
                        <td>
                          <a href="{% url 'modelos_rutinas_show' rutina.id %}" title="Ver Rutina"><i class='bx bx-dumbbell bx-sm' ></i> </a>
                          <a href="{% url 'modelos_rutinas_update' rutina.id %}" title="Editar"><i class='bx bxs-edit bx-sm' ></i> </a>
                          <a href="{% url 'modelos_rutinas_delete' rutina.id %}" title="Borrar"><i class='bx bx-trash bx-sm'></i> </a>
                      </tr>
                      {% endfor %}

                      
                    </tbody>
                  </table>
                  
                </div>
                {% else %}
                  <div class="row">
                    <div class="col-12">
                      <p>No existen registros de socios para mostrar.-</p>
                    </div>
                  </div>
                    
                  {% endif %}
                </div>
                <!-- /.card-body -->
              </div>

            </div>
            <!-- /.col-md-6 -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->

      <!-- MODAL GENERAR CUOTAS -->
      <!-- Modal -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalCenterTitle">Crear Rutina</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="{% url 'modelos_rutinas_create' %}" method="POST">
              {% csrf_token %}
              <div class="modal-body">
                {% comment %} <p style="text-align: center;">Va a generar pagos para todos los socios ACTIVOS con los valores seleccionados debajo</p> {% endcomment %}

                <div class="row">
                  <div class="col-12">
                      <div class="form-group">
                          <label for="titulo">Titulo</label>
                          {{form.titulo}}
                      </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-12">
                      <div class="form-group">
                          <label for="descripcion">Descripcion</label>
                          {{form.descripcion}}
                      </div>
                  </div>
                </div>

              </div>
              <div class="modal-footer">
                <button type="button" tabindex="-1" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary"><i class='bx bx-plus-medical'></i> Crear</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- FIN MODAL GENERAR CUOTAS -->
{% endblock content %}

{% block scripts %}
<script>
  $(function () {
    $('#exampleModalCenter').on('shown.bs.modal', function (e) {
      $('#id_titulo').focus();
    })
  });
</script>
{% endblock scripts %}